=== utcarnivaldayo/portfolio/portfolio/app/frontend/src/schema/newsItem.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "items": {
    "properties": {
      "date": {
        "format": "date",
        "type": "string"
      },
      "link": {
        "format": "uri",
        "type": "string"
      },
      "newsId": {
        "minimum": 1,
        "type": "integer"
      },
      "tags": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "title": {
        "type": "string"
      }
    },
    "required": [
      "date",
      "link",
      "newsId",
      "tags",
      "title"
    ],
    "type": "object"
  },
  "type": "array"
}

=== utcarnivaldayo/portfolio/portfolio/app/frontend/src/assets/masterdata/newsMaster.json
[
  {
    "date": "2021-01-12",
    "link": "https://utcarnivaldayo.github.io/harigae_port/",
    "newsId": 1,
    "tags": [
      "お知らせ",
      "bootstrap",
      "webassembly",
      "就活"
    ],
    "title": "旧ポートフォリオサイトの公開"
  },
  {
    "date": "2022-12-31",
    "link": "https://zenn.dev/utcarnivaldayo/articles/ffeed5ac2e62bb",
    "newsId": 2,
    "tags": [
      "技術記事",
      "zenn",
      "統計",
      "数値計算",
      "rust"
    ],
    "title": "インクリメンタルに複数の時系列データに対する平均・標準偏差を計算する"
  },
  {
    "date": "2024-01-13",
    "link": "https://zenn.dev/numagotatu/articles/2024-01-07-deploy-github-pages",
    "newsId": 3,
    "tags": [
      "技術記事",
      "zenn",
      "react",
      "github",
      "githubactions"
    ],
    "title": "React コードを隠したまま GitHub Pages でサイトを公開する"
  },
  {
    "date": "2024-04-13",
    "link": "https://zenn.dev/numagotatu/articles/2024-04-07-docker-on-multipass",
    "newsId": 4,
    "tags": [
      "技術記事",
      "zenn",
      "docker",
      "multipass",
      "ubuntu"
    ],
    "title": "Docker 環境を作るなら Ubuntu のクロスプラットフォームな仮想化ツール Multipass を使おう"
  },
  {
    "date": "2024-06-28",
    "link": "https://zenn.dev/numagotatu/articles/2024-04-13-init-vscode-extension",
    "newsId": 5,
    "tags": [
      "技術記事",
      "zenn",
      "vscode"
    ],
    "title": "Workspace 単位で Remote-SSH 先のサーバーに VSCode 拡張を自動インストールしたい"
  },
  {
    "date": "2024-06-30",
    "link": "https://zenn.dev/numagotatu/articles/2024-06-23-pants-build-docker-build",
    "newsId": 6,
    "tags": [
      "技術記事",
      "zenn",
      "docker",
      "pants"
    ],
    "title": "pants でスマートな docker build をしよう!"
  },
  {
    "date": "2024-12-29",
    "link": "/#",
    "newsId": 7,
    "tags": [
      "お知らせ",
      "typescript",
      "react",
      "tailwindcss",
      "tanstackrouter"
    ],
    "title": "TS + React + tailwindcss でポートフォリオサイトのリニューアル"
  },
  {
    "date": "2024-12-30",
    "link": "https://github.com/utcarnivaldayo/multipasser",
    "newsId": 8,
    "tags": [
      "お知らせ",
      "monorepo",
      "multipass",
      "bash",
      "docker"
    ],
    "title": "ローカル仮想環境 monorepo テンプレート 「multipasser」を公開"
  },
  {
    "date": "2025-04-04",
    "link": "https://zenn.dev/numagotatu/articles/2025-04-04-dynamo-multiple-json-store",
    "newsId": 9,
    "tags": [
      "技術記事",
      "zenn",
      "aws",
      "dynamodb",
      "cli"
    ],
    "title": "AWS CLI で DynamoDB のデータ型記述子なしに複数 json データ投入"
  },
  {
    "date": "2025-06-08",
    "link": "https://zenn.dev/utcarnivaldayo/articles/2025-06-08-tbls-aurora-serverless-install-tips",
    "newsId": 10,
    "tags": [
      "技術記事",
      "zenn",
      "aws",
      "aurora",
      "postgresql",
      "go",
      "tbls"
    ],
    "title": "tbls を Aurora Serverless・DSQL で使おうとしてハマったときの TIPS"
  },
  {
    "date": "2025-06-22",
    "link": "https://zenn.dev/utcarnivaldayo/articles/2025-06-22-pulumi-ts-svless",
    "newsId": 11,
    "tags": [
      "技術記事",
      "zenn",
      "aws",
      "pulumi",
      "typescript",
      "serverless"
    ],
    "title": "「そのインフラ、次世代 IaC Pulumi を使って TypeScript で書いてみませんか？」という記事で Zenn 主催の TypeScript 記事コンテストに参加"
  },
  {
    "date": "2025-06-22",
    "link": "https://zenn.dev/utcarnivaldayo/books/pulumi-lambadlith",
    "newsId": 12,
    "tags": [
      "書籍",
      "zenn",
      "aws",
      "pulumi",
      "typescript",
      "serverless"
    ],
    "title": "Zenn book 「もう TypeScript だけでいい。次世代 IaC Pulumi で最高の体験にする AWS サーバレスアプリ開発」を公開"
  }
]
