=== utcarnivaldayo/portfolio/portfolio/app/frontend/src/schema/sandboxItem.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "items": {
    "properties": {
      "date": {
        "format": "date",
        "type": "string"
      },
      "link": {
        "format": "uri",
        "type": "string"
      },
      "sandboxId": {
        "minimum": 1,
        "type": "integer"
      },
      "tags": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "title": {
        "type": "string"
      }
    },
    "required": [
      "date",
      "link",
      "sandboxId",
      "tags",
      "title"
    ],
    "type": "object"
  },
  "type": "array"
}

=== utcarnivaldayo/portfolio/portfolio/app/frontend/src/assets/masterdata/sandboxMaster.json
[
  {
    "date": "2021-01-12",
    "link": "https://utcarnivaldayo.github.io/harigae_port/",
    "sandboxId": 1,
    "tags": [
      "ポートフォリオサイト",
      "bootstrap",
      "webassembly",
      "就活"
    ],
    "title": "新卒就活時のポートフォリオサイト"
  },
  {
    "date": "2024-12-29",
    "link": "/#",
    "sandboxId": 2,
    "tags": [
      "ポートフォリオサイト",
      "typescript",
      "react",
      "tailwindcss",
      "tanstackrouter"
    ],
    "title": "react で作ったポートフォリオサイト"
  },
  {
    "date": "2024-12-30",
    "link": "https://github.com/utcarnivaldayo/multipasser",
    "sandboxId": 3,
    "tags": [
      "monorepo",
      "ubuntu",
      "multipass",
      "bash",
      "docker"
    ],
    "title": "ローカル仮想環境 monorepo テンプレート 「multipasser」"
  }
]
